import Head from 'next/head'
import React from 'react'
import styles from '../page.module.css';
import Sidebar from './Sidebar';
import Link from 'next/link';
import Navbar from '../nav/Navbar';
const Layout = ({title , container}) => {
  return (
    <div className={styles.page}>
        <Head>
            <meta name="description" content="Generated by tarekkhater" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
            <title key="title">
                {title? title + " - Tarek Khater" : "Tarek Khater"}
            </title>
        </Head>
        <div className={styles.container}>
            <Sidebar />  
            <div className={styles.content}>
                <main className={styles.main}>
                    <Navbar />
                    {container}
                </main>
            <footer className={styles.footer}>
                <p>Copyright © 2022 tarekkhater</p>
            </footer>
        </div>
            
        </div>
        
        
    </div>
  )
}

export default Layout